# Generated by Django 3.0 on 2020-02-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatchings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinghistory',
            name='matchingInProgress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchinghistory',
            name='open_matching_to_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchinghistory',
            name='open_matching_to_employer',
            field=models.BooleanField(default=True),
        ),
    ]
