# Generated by Django 3.0 on 2020-02-05 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0010_auto_20200205_0041'),
        ('jobmatchings', '0002_auto_20200204_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='jobApplication',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobapplications.JobApplication'),
        ),
    ]
