# Generated by Django 3.0 on 2020-03-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatchings', '0004_matchinghistory_isopentopublic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchinghistory',
            name='isOpenToPublic',
        ),
        migrations.AddField(
            model_name='match',
            name='isOpenToPublic',
            field=models.BooleanField(default=False),
        ),
    ]
