# Generated by Django 3.0 on 2020-01-06 22:41

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joblistings', '0011_auto_20200106_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=40)),
                ('lastName', models.CharField(default='', max_length=40)),
                ('preferredName', models.CharField(default='', max_length=40)),
                ('studentID', models.CharField(default='', max_length=40)),
                ('category', models.CharField(choices=[('ANY', 'Any Category'), ('E_Aero_Mech', 'GCS Engineering - Aerospace & Mechanical'), ('E_Elec', 'GCS Engineering - Electrical'), ('E_Ind', 'GCS Engineering - Industrial'), ('E_QS', 'GCS Engineering - Quality System'), ('E_Soft', 'GCS Engineering and Computer Science - Computer, Information Security & Software'), ('E_Other', 'GCS Engineering - Other'), ('F_A_Design', 'Fine Arts - Computational Arts & Design'), ('J_Acc_Fin', 'JMSB - Accounting & Finance'), ('J_HR_Mar', 'JMSB - HR & Marketing'), ('J_Bus', 'JMSB - Business Administration'), ('J_Man', 'JMSB - Management & Supply Chain Operation Management'), ('J_Other', 'JMSB - Other'), ('A_Acc', 'Arts and Science - Actuarial Mathematics & Finance'), ('A_Econ', 'Arts and Science - Economics'), ('A_Math_Phy', 'Arts and Science - Mathematics & Physics'), ('A_Pol', 'Arts and Science - Political Science'), ('A_BIO_CHEM', 'Arts and Science - Biology & Chemistry'), ('A_Jou', 'Arts and Science - Journalism'), ('A_Tr', 'Arts and Science - Translation'), ('A_Other', 'Arts and Science - Other')], default='Any', max_length=40)),
                ('location', models.CharField(default='', max_length=40)),
                ('skillList', models.CharField(default='', max_length=100)),
                ('aboutYou', tinymce.models.HTMLField(default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='joblistings.Job')),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=40)),
                ('proficiencyPercentage', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(default='', max_length=40)),
                ('document', models.FileField(default='', upload_to='user/document/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('JobApplication', models.ManyToManyField(to='jobapplications.JobApplication')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(default='', max_length=40)),
                ('resume', models.FileField(default='', upload_to='user/resume/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('JobApplication', models.ManyToManyField(to='jobapplications.JobApplication')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='', max_length=40)),
                ('title', models.CharField(default='', max_length=40)),
                ('period', models.CharField(default='', max_length=40)),
                ('description', tinymce.models.HTMLField(default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('JobApplication', models.ManyToManyField(to='jobapplications.JobApplication')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(default='', max_length=40)),
                ('title', models.CharField(default='', max_length=40)),
                ('period', models.CharField(default='', max_length=40)),
                ('description', tinymce.models.HTMLField(default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('JobApplication', models.ManyToManyField(to='jobapplications.JobApplication')),
            ],
        ),
        migrations.CreateModel(
            name='coverLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(default='', max_length=40)),
                ('coverLetter', models.FileField(default='', upload_to='user/coverletter/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('JobApplication', models.ManyToManyField(to='jobapplications.JobApplication')),
            ],
        ),
    ]
