# Generated by Django 3.0 on 2020-01-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='language',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='location',
        ),
    ]
