# Generated by Django 3.0 on 2020-02-02 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Coop Review'), ('Submitted', 'Submitted to Employer'), ('Interviewing', 'Selected for Interview'), ('Not Selected', 'Not Selected'), ('Ranked', 'Ranked by Employer'), ('Matched', 'Matched'), ('Not Matched', 'Not Matched'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerRank', models.IntegerField(default=1000)),
                ('userRank', models.IntegerField(default=1000)),
                ('preferredName', models.CharField(default='', max_length=40)),
                ('status', models.CharField(choices=[('Pending', 'Pending Coop Review'), ('Submitted', 'Submitted to Employer'), ('Interviewing', 'Selected for Interview'), ('Not Selected', 'Not Selected'), ('Ranked', 'Ranked by Employer'), ('Matched', 'Matched'), ('Not Matched', 'Not Matched'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='joblistings.Job')),
                ('jobApplication', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobapplications.JobApplication')),
            ],
        ),
    ]
