# Generated by Django 3.0 on 2020-01-26 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapplications', '0002_jobapplication_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
