# Generated by Django 3.0 on 2020-01-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0002_auto_20200107_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='aboutYou',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='skillList',
        ),
    ]
