# Generated by Django 3.0 on 2020-02-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0004_auto_20200204_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='preferredName',
        ),
        migrations.AddField(
            model_name='ranking',
            name='is_ranking_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Coop Review'), ('Not Approved', 'Not Approved'), ('Submitted', 'Submitted to Employer'), ('Interviewing', 'Selected for Interview'), ('Not Selected', 'Not Selected'), ('Ranked', 'Ranked by Employer'), ('Matched', 'Matched'), ('Not Matched', 'Not Matched'), ('Closed', 'Closed')], default='Interviewing', max_length=20),
        ),
    ]
