# Generated by Django 3.0 on 2020-02-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0007_auto_20200204_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='is_ranking_open',
            new_name='is_ranking_open_for_employer',
        ),
        migrations.AddField(
            model_name='ranking',
            name='is_ranking_open_for_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
