# Generated by Django 3.0 on 2020-02-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0008_auto_20200204_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='userRank',
            new_name='candidateRank',
        ),
    ]
