# Generated by Django 3.0 on 2020-04-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplications', '0010_auto_20200205_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='preferredName',
        ),
    ]
