# Generated by Django 3.0 on 2020-03-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='program',
            field=models.CharField(choices=[('ANY', 'Any Category'), ('E_Aero_Mech', 'GCS Engineering - Aerospace & Mechanical'), ('E_Elec', 'GCS Engineering - Electrical'), ('E_Ind', 'GCS Engineering - Industrial'), ('E_QS', 'GCS Engineering - Quality System'), ('E_Soft', 'GCS Engineering and Computer Science - Computer, Information Security & Software'), ('E_Other', 'GCS Engineering - Other'), ('F_A_Design', 'Fine Arts - Computational Arts & Design'), ('J_Acc_Fin', 'JMSB - Accounting & Finance'), ('J_HR_Mar', 'JMSB - HR & Marketing'), ('J_Bus', 'JMSB - Business Administration'), ('J_Man', 'JMSB - Management & Supply Chain Operation Management'), ('J_Other', 'JMSB - Other'), ('A_Acc', 'Arts and Science - Actuarial Mathematics & Finance'), ('A_Econ', 'Arts and Science - Economics'), ('A_Math_Phy', 'Arts and Science - Mathematics & Physics'), ('A_Pol', 'Arts and Science - Political Science'), ('A_BIO_CHEM', 'Arts and Science - Biology & Chemistry'), ('A_Jou', 'Arts and Science - Journalism'), ('A_Tr', 'Arts and Science - Translation'), ('A_Other', 'Arts and Science - Other')], default='ANY', max_length=20),
        ),
    ]
