# Generated by Django 3.0 on 2020-01-31 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='creditCompleted',
            field=models.FloatField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='candidate',
            name='creditLeft',
            field=models.FloatField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gpa',
            field=models.FloatField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='candidate',
            name='internationalStudent',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='candidate',
            name='timeCommitment',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='candidate',
            name='transcript',
            field=models.FileField(default='', upload_to='candidate/transcript/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='travel',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PreferredName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferredName', models.CharField(default='', max_length=40)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Other', 'Other (Please specify below)')], default='', max_length=40)),
                ('fluency', models.CharField(choices=[(0, 'Elementary Proficiency'), (35, 'Limited Working Proficiency'), (60, 'Professional Working Proficiency'), (80, 'Full Working Proficiency'), (100, 'Native or Bilingual Proficiency')], default='', max_length=40)),
                ('details', models.CharField(default='', max_length=40)),
                ('user', models.ForeignKey(default='', max_length=40, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
