# Generated by Django 3.0 on 2020-02-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200130_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_confirmed',
        ),
        migrations.AddField(
            model_name='user',
            name='is_downloading_protecting_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='protect_file_temp_download_key',
            field=models.CharField(default='', max_length=40),
        ),
    ]
