# Generated by Django 3.0 on 2020-02-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200202_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_downloading_protecting_files',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
