# Generated by Django 3.0 on 2020-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200428_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Coop Review'), ('Not Approved', 'Not approved'), ('Approved', 'Approved')], default='Pending Review', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Coop Review'), ('Not Approved', 'Not approved'), ('Approved', 'Approved')], default='Pending Review', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='preferredName',
            field=models.CharField(default='', max_length=40),
        ),
    ]
