# Generated by Django 3.0 on 2020-02-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Coop Review'), ('Not Approved', 'Not Approved'), ('Not Approved', 'Pending Coop Review'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Pending', max_length=20),
        ),
    ]
