# Generated by Django 3.0 on 2020-04-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200204_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='videoLink',
            field=models.CharField(default='https://www.youtube.com/watch?v=NwAxNFwEEbM', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='videoType',
            field=models.CharField(default='youtube', max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Coop Review'), ('Not Approved', 'Not approved'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
