# Generated by Django 3.0 on 2020-01-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Coop Review'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Pending', max_length=20),
        ),
    ]
