# Generated by Django 3.0 on 2019-12-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20191225_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
    ]
