# Generated by Django 3.0 on 2019-12-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20191225_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='company-logo-1', upload_to='images/company/'),
        ),
    ]
