# Generated by Django 3.0 on 2019-12-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(default='images/company/company-logo-1', upload_to='images/company/'),
        ),
    ]
