# Generated by Django 3.0 on 2020-02-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Coop Review'), ('Not Approved', 'Not Approved'), ('Waiting', 'Collecting applications'), ('Review', 'Open for Review'), ('Interviewing', 'Intervierwing'), ('Not Approved', 'Not Approved'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
