# Generated by Django 3.0 on 2019-12-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='Montreal', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='expirationDate',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Montreal', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='postcode',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='job',
            name='responsabilities',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='job',
            name='salaryRange',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='yourLocation',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
