# Generated by Django 3.0 on 2020-02-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200202_0115'),
        ('joblistings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobaccesspermission',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='jobAccessPermission',
            field=models.ManyToManyField(to='joblistings.JobAccessPermission'),
        ),
        migrations.RemoveField(
            model_name='jobaccesspermission',
            name='employer',
        ),
        migrations.AddField(
            model_name='jobaccesspermission',
            name='employer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer'),
        ),
    ]
