# Generated by Django 3.0 on 2020-02-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200202_0115'),
        ('joblistings', '0002_auto_20200203_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobAccessPermission',
            field=models.ManyToManyField(to='accounts.Employer'),
        ),
        migrations.DeleteModel(
            name='JobAccessPermission',
        ),
    ]
