# Generated by Django 3.0 on 2020-01-26 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200125_1339'),
        ('joblistings', '0002_jobpdfdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAccessPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ManyToManyField(to='accounts.Employer')),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='joblistings.Job')),
            ],
        ),
    ]
