# Generated by Django 3.0 on 2020-02-05 13:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0002_auto_20200204_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=tinymce.models.HTMLField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsabilities',
            field=tinymce.models.HTMLField(default='', max_length=10000),
        ),
    ]
