# Generated by Django 3.0 on 2020-01-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0003_jobaccesspermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Coop Review'), ('Waiting', 'Collecting applications'), ('Review', 'Open for Review'), ('Interviewing', 'Intervierwing'), ('Not Approved', 'Not Approved'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
