# Generated by Django 3.0 on 2020-03-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0003_auto_20200205_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='filled',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
