# Generated by Django 3.0 on 2019-12-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0003_auto_20191224_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
