# Generated by Django 3.0 on 2019-12-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0004_auto_20191225_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('ANY', 'Any'), ('E_Aero_Mech', 'Engineering - Aerospace & Mechanical'), ('E_Elec', 'Engineering - Electrical'), ('E_Ind', 'Engineering - Industrial'), ('E_QS', 'Engineering - Quality System'), ('E_Soft', 'Engineering and Computer Science - Computer, Information Security & Software'), ('E_Other', 'Engineering - Other'), ('F_A_Design', 'Fine Arts - Computational Arts & Design'), ('J_Acc_Fin', 'JMSB - Accounting & Finance'), ('J_HR_Mar', 'JMSB - HR & Marketing'), ('J_Bus', 'JMSB - Business Administration'), ('J_Man', 'JMSB - Management & Supply Chain Operation Management'), ('J_Other', 'JMSB - Other'), ('A_Acc', 'Arts and Science - Actuarial Mathematics & Finance'), ('A_Econ', 'Arts and Science - Economics'), ('A_Math_Phy', 'Arts and Science - Mathematics & Physics'), ('A_Pol', 'Arts and Science - Political Science'), ('A_BIO_CHEM', 'Arts and Science - Biology & Chemistry'), ('A_Jou', 'Arts and Science - Journalism'), ('A_Tr', 'Arts and Science - Translation'), ('A_Other', 'Arts and Science - Other')], default='Any', max_length=30),
        ),
    ]
