# Generated by Django 3.0 on 2020-03-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0004_auto_20200316_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending Coop Review'), ('Not Approved', 'Not Approved'), ('Approved', 'Approved'), ('Interviewing', 'Interviewing'), ('Filled', 'Filled'), ('Partially Filled', 'Partially Filled'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
