# Generated by Django 3.0 on 2019-12-29 18:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0007_auto_20191229_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=tinymce.models.HTMLField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsabilities',
            field=tinymce.models.HTMLField(default='', max_length=2000),
        ),
    ]
