# Generated by Django 3.0 on 2019-12-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0008_auto_20191229_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
    ]
