# Generated by Django 3.0 on 2020-01-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0010_job_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('ANY', 'Any Category'), ('E_Aero_Mech', 'GCS Engineering - Aerospace & Mechanical'), ('E_Elec', 'GCS Engineering - Electrical'), ('E_Ind', 'GCS Engineering - Industrial'), ('E_QS', 'GCS Engineering - Quality System'), ('E_Soft', 'GCS Engineering and Computer Science - Computer, Information Security & Software'), ('E_Other', 'GCS Engineering - Other'), ('F_A_Design', 'Fine Arts - Computational Arts & Design'), ('J_Acc_Fin', 'JMSB - Accounting & Finance'), ('J_HR_Mar', 'JMSB - HR & Marketing'), ('J_Bus', 'JMSB - Business Administration'), ('J_Man', 'JMSB - Management & Supply Chain Operation Management'), ('J_Other', 'JMSB - Other'), ('A_Acc', 'Arts and Science - Actuarial Mathematics & Finance'), ('A_Econ', 'Arts and Science - Economics'), ('A_Math_Phy', 'Arts and Science - Mathematics & Physics'), ('A_Pol', 'Arts and Science - Political Science'), ('A_BIO_CHEM', 'Arts and Science - Biology & Chemistry'), ('A_Jou', 'Arts and Science - Journalism'), ('A_Tr', 'Arts and Science - Translation'), ('A_Other', 'Arts and Science - Other')], default='Any', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(choices=[('None', 'Country'), ('CA', 'Canada'), ('US', 'USA'), ('Other-Europe', 'Other- Europe'), ('Other-Asia', 'Other- Asia'), ('Other', 'Other')], default='Canada', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='expirationDate',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Montreal', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='postcode',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='salaryRange',
            field=models.CharField(default='N/A', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='startDate',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='yourLocation',
            field=models.CharField(default='', max_length=40),
        ),
    ]
